import type { ApiItem } from '@/types';

export const MOCK_APIS: ApiItem[] = [
    {
        id: 0,
        name: 'Bitcoin Price API',
        description: 'Get current Bitcoin price from CoinDesk. Returns real-time USD, GBP, and EUR prices with exchange rate data.',
        endpoint: 'https://api.coindesk.com/v1/bpi/currentprice.json',
        priceSats: 100,
        owner: 'bc1q...demo1',
        totalCalls: 12847,
        active: true,
        category: 'Finance',
        isMock: true,
    },
    {
        id: 1,
        name: 'Random User Generator',
        description: 'Generate random user profiles with name, email, avatar, and location. Perfect for testing and prototyping.',
        endpoint: 'https://randomuser.me/api/',
        priceSats: 50,
        owner: 'bc1q...demo2',
        totalCalls: 8432,
        active: true,
        category: 'Utilities',
        isMock: true,
    },
    {
        id: 2,
        name: 'IP Geolocation API',
        description: 'Get geolocation data for any IP address including country, city, timezone, and ISP information.',
        endpoint: 'https://ipapi.co/json/',
        priceSats: 200,
        owner: 'bc1q...demo3',
        totalCalls: 5691,
        active: true,
        category: 'Data',
        isMock: true,
    },
    {
        id: 3,
        name: 'Joke API',
        description: 'Get random programming jokes and puns. Supports different categories: programming, dark, pun, misc.',
        endpoint: 'https://v2.jokeapi.dev/joke/Programming?type=single',
        priceSats: 25,
        owner: 'bc1q...demo4',
        totalCalls: 21503,
        active: true,
        category: 'Entertainment',
        isMock: true,
    },
    {
        id: 4,
        name: 'Dog Image API',
        description: 'Get random dog images from a collection of over 20,000 photos. Returns a direct image URL.',
        endpoint: 'https://dog.ceo/api/breeds/image/random',
        priceSats: 30,
        owner: 'bc1q...demo5',
        totalCalls: 15782,
        active: true,
        category: 'Media',
        isMock: true,
    },
    {
        id: 5,
        name: 'Cat Facts API',
        description: 'Random cat facts delivered via API. Educational and entertaining feline data.',
        endpoint: 'https://catfact.ninja/fact',
        priceSats: 20,
        owner: 'bc1q...demo6',
        totalCalls: 9234,
        active: true,
        category: 'Entertainment',
        isMock: true,
    },
    {
        id: 6,
        name: 'Blockchain Stats',
        description: 'Real-time Bitcoin blockchain statistics including hashrate, difficulty, and mempool data.',
        endpoint: 'https://api.blockchain.info/stats',
        priceSats: 500,
        owner: 'bc1q...demo7',
        totalCalls: 3891,
        active: true,
        category: 'Blockchain',
        isMock: true,
    },
    {
        id: 7,
        name: 'Exchange Rates',
        description: 'Latest foreign exchange rates with USD as base. Covers 170+ currencies worldwide.',
        endpoint: 'https://open.er-api.com/v6/latest/USD',
        priceSats: 150,
        owner: 'bc1q...demo8',
        totalCalls: 6742,
        active: true,
        category: 'Finance',
        isMock: true,
    },
];

export const CATEGORIES = ['All', 'Finance', 'Data', 'Utilities', 'Entertainment', 'Media', 'Blockchain'];
